apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: redis
spec:
  components:
  - name: redis
    type: helm
    properties:
      chart: redis
      url: https://charts.bitnami.com/bitnami