apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dapr
spec:
  components:
  - name: dapr
    type: helm
    properties:
      # production config: https://docs.dapr.io/zh-hans/operations/hosting/kubernetes/kubernetes-production/
      # helm chart config: https://github.com/dapr/dapr/blob/master/charts/dapr/README.md
      chart: dapr
      version: 1.5.0
      url: https://dapr.github.io/helm-charts