apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: dapr-ingress
spec:
  components:
  - name: dapr-ingress
    type: raw
    properties:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target:  /$2
      spec:
        rules:
        - http:
            paths:
            - backend:
                service:
                  name: dapr-dashboard
                  port:
                    number: 8080
              pathType: Prefix
              path: /dapr-dashboard(/|$)(.*)
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dapr-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#   - http:
#       paths:
#       - backend:
#           service:
#             name: dapr-dashboard
#             port:
#               number: 8080
#         pathType: Prefix
#         path: /dapr-dashboard(/|$)(.*)